const items = document.querySelector('#items');
console.log(items.parentElement);
const headerTitle = document.querySelector('#header-title');
const newElement = document.createElement('h1');
newElement.textContent = "HEllo";
headerTitle.parentElement.insertBefore(newElement, headerTitle);
const item1 = document.querySelector('.list-group-item');
const newItem = document.createElement('li');
newItem.setAttribute('class', 'list-group-item');
newItem.textContent = 'HEllo';
items.insertBefore(newItem, item1);